In [1]:
from typing import Any

import pandas as pd
from pandas import Series, DataFrame

In [2]:
data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['id', 'salary']).astype({'id':'int64', 'salary':'int64'})

In [3]:
employee

   id  salary
0   1     100
1   2     200
2   3     300



Write a solution to find the second highest distinct salary from the Employee table. If there is no second highest salary, return null (return None in Pandas).

In [8]:
employee.sort_values(ascending=False,by = "salary").iloc[[1]]

   id  salary
1   2     200

In [10]:
import pandas as pd
import numpy as np


data = [[1, 100], [2, 200], [3, 300]]
def second_highest_salary(employee: pd.DataFrame) -> Series[Any] | DataFrame:
    if employee.empty:
        employee["SecondHighestSalary"] = np.nan
        return employee["SecondHighestSalary"]

    else :
        return employee.sort_values(ascending=False,by = "salary").iloc[[1]]

NameError: name 'Series' is not defined